<a href="https://colab.research.google.com/github/rbdus0715/kaggle/blob/main/study/sklearn/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **데이터 인코딩**

- 레이블 인코딩
- 원-핫 인코딩

In [1]:
# 레이블 인코딩
from sklearn.preprocessing import LabelEncoder

items = ['tv', '냉장고', '쇼파', '컴퓨터', 'tv']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 인코딩 클래스
print(encoder.classes_)

# 인코딩 결과
print(labels)

# 디코딩
print(encoder.inverse_transform([2, 3, 3, 0, 1]))

['tv' '냉장고' '쇼파' '컴퓨터']
[0 1 2 3 0]
['쇼파' '컴퓨터' '컴퓨터' 'tv' '냉장고']


In [2]:
# 원-핫 인코딩
from sklearn.preprocessing import OneHotEncoder

items = ['tv', '냉장고', '쇼파', '컴퓨터', 'tv']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels = labels.reshape(-1, 1) # 2차원 데이터로 변환

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]
(5, 4)


In [3]:
# 판다스의 get_dummies를 통해 원-핫 인코딩 더 쉽게 하기
import pandas as pd

df = pd.DataFrame({
    'items': ['tv', '냉장고', '쇼파', '컴퓨터', 'tv']
})

pd.get_dummies(df)

items_tv  items_냉장고  items_쇼파  items_컴퓨터
0         1          0         0          0
1         0          1         0          0
2         0          0         1          0
3         0          0         0          1
4         1          0         0          0

## **피처 스케일링과 정규화**

(1) 표준화 - StandardScaler : 평균이 0이고 분산이 1인 분포로 변환

In [5]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print(iris_df.mean())
print(iris_df.var())

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print(iris_df_scaled.mean())
print(iris_df_scaled.var())

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


(2) 정규화 : 데이터를 일정 범위 내의 수치로 변환하는 것

In [11]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print(iris_df_scaled.min())
print(iris_df_scaled.max())

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
