<a href="https://colab.research.google.com/github/rbdus0715/kaggle/blob/main/study/numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## **1. ndarray**

- 넘파이에서 유용하게 사용될 수 있는 여러 속성을 가진 배열 객체
- ndarray 객체는 np.array() 함수를 통해 생성한다.
- ndarray 생성자를 통해 만들수도 있지만 doc에서는 array()를 통하는 것을 추천한다.

- 멤버변수와 멤버함수에 대한 자세한 내용은 [링크](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)를 확인한다.

    - type(ndarray)
    - .shape
    - .ndim
    - .dtype
    - 자동 타입 변환
    - 강제 타입 변환 .astype

In [2]:
# 넘파이 배열 생성하기
# np.array() 함수 사용
array1 = np.array([1, 2, 3])

# 데이터타입
print(type(array1))

# 배열 모양
print(array1.shape)

# 차원
print(array1.ndim)

# 객체 내의 데이터값의 데이터타입
print(array1.dtype)

# 데이터타입이 다른 것이 데이터로 들어간다면 더 큰 데이터 타입으로 통일됨
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2.dtype)

# 데이터타입 변경하기
array3 = array1.astype('float64')
print(array3.dtype)

<class 'numpy.ndarray'>
(3,)
1
int64
<U21
float64


## **2. ndarray 초기화 메서드**

- 특정 크기와 차원을 가진 배열을 연속값, 0, 1로 초기화 해야하는 경우
- arange, zeros, ones

In [3]:
# 연속배열
seq_array1 = np.arange(10)
seq_array2 = np.arange(3, 8)
seq_array3 = np.arange(3, 8, 2)
print(seq_array1, seq_array2, seq_array3)

# 모두 0으로 초기화
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)

# 모두 1로 초기화
one_array = np.ones((3,2), dtype='float32')
print(one_array)

[0 1 2 3 4 5 6 7 8 9] [3 4 5 6 7] [3 5 7]
[[0 0]
 [0 0]
 [0 0]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


## **3. ndarray 차원과 크기 변경하기**

- reshape

In [4]:
array1 = np.arange(10)

array2 = array1.reshape(2, 5)
print(array2)

array3 = array1.reshape(5, 2)
print(array3)

# -1는 예상되는 크기로 알아서 지정해서 reshape
array4 = array1.reshape(-1, 5)
print(array4)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## **4. ndarray 인덱싱**

- 특정 데이터만 추출
- 슬라이싱
- 팬시 인덱싱
- 불린 인덱싱

In [5]:
# 특정 데이터 추출
array1 = np.arange(1, 10)
print(array1)
array2 = array1.reshape(3, 3)
print(array2[2, 2])

# 슬라이싱 [시작 인덱스:시작 인덱스부터 슬라이싱 할 칸 수]
array3 = array1[0:3]
print(array3)

# 팬시 인덱싱 : 슬라이싱과 인덱스를 복합적으로 사용
array4 = array2[[0,1], 2]
print(array4)

# 불린 인덱싱 (필터링 기능)
array3 = array1[array1 > 5]
print(array1>5)
print(array3)

[1 2 3 4 5 6 7 8 9]
9
[1 2 3]
[3 6]
[False False False False False  True  True  True  True]
[6 7 8 9]


## **5. 정렬**

- 원본을 보존하는 정렬 vs 원본 자체를 정렬
- 내림차순 정렬 오름차순 정렬 이후 [::-1]

In [6]:
# 원본 보존
org_array = np.array([3, 1, 9, 5])
sort_array = np.sort(org_array)
print(sort_array)
print(org_array)

# 원본 자체를 정렬, 정렬된 배열을 반환하지 않는다
sort_array2 = org_array.sort()
print(sort_array2)
print(org_array)

# 내림차순 정렬
print(org_array[::-1])

[1 3 5 9]
[3 1 9 5]
None
[1 3 5 9]
[9 5 3 1]


- 2차원 행렬에서 정렬
- 정렬된 행렬의 인덱스 반환 np.argsort()

In [7]:
# 원하는 축을 기준으로 정렬
array2d = np.array([[8, 12],
                    [7, 1]])

sort_axis0 = np.sort(array2d, axis=0)
print(sort_axis0)

sort_axis1 = np.sort(array2d, axis=1)
print(sort_axis1)

# 정렬된 행렬의 인덱스 반환
org_array = np.array([3, 1, 9, 5])
print(np.argsort(org_array))

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]
[1 0 3 2]


## **6. 행렬 연산**

- 행렬 내적(행렬 곱) np.dot()
- 전치행렬 np.transpose()

In [8]:
# (2, 3) * (3, 2) = (2, 2)
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

dot_product = np.dot(A, B)
print(dot_product)

print(np.transpose(A))

[[ 58  64]
 [139 154]]
[[1 4]
 [2 5]
 [3 6]]
